### ISSUE TITLE
Illegal instruction upscayl 2.8.0+

### ISSUE THREAD

**Issue by AngryPenguinPL** [upscayl/upscayl#659]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).
- [ ] I am using Windows and I've tried [common troubleshooting steps](https://github.com/upscayl/upscayl/wiki/Troubleshooting).

### Describe the Bug

Hi.

Last working version of upscayl is 2.7.5.  After upgrading to 2.8.0 and all next up to current 2.9.8 the application has stopped working.
In console I see error: `Illegal instruction (core dumped)`.

journalctl show me this:
```
Process 34732 (upscayl) of user 1001 dumped core.
                                                             
Stack trace of thread 34732:
#0  0x00007f638c530d83 n/a (/home/x/Desktop/upscayl-2.9.8 linux/resources/app.asar.unpacked/node_modules/sharp/vendor/8.14.5/linux-x64/lib/libvips-cpp.so.42 + 0x330d83)
#1  0x8c53b8eb00000000 n/a (n/a + 0x0)
ELF object binary architecture: AMD x86-64
```

By illegal instruction I mean that the application started using something that my processor no longer supports? Or maybe it's just a compilation error with the wrong flag?

Anyway that all changes between 2.7.5 and 2.8.0 https://github.com/upscayl/upscayl/compare/v2.7.5...v2.8.0

Tested on appimage version and prebuild linux binary from .zip archive. Both same error.

I can reproduce this problem in two operating systems: ubuntu 24.04 and openmandriva cooker.
I have old cpu Phenom II X6 and Radeon RX580 with Vulkan support.

### To Reproduce

- Try open upscayl on older CPU like phenom II
- See error in terminal

### Version (or commit hash)

2.9.8

### Did you download Upscayl from the Mac App Store?

- [ ] Yes, I downloaded Upscayl from the Mac App Store!

### Select your Operating System

Linux

### OS Version

Ubuntu 24.04, OpenMandriva Cooker

### GPU Name

RX580

### Expected Behavior

All works fine

### Paste the logs

```sh
journalctl show me this:

Process 34732 (upscayl) of user 1001 dumped core.
                                                             
Stack trace of thread 34732:
#0  0x00007f638c530d83 n/a (/home/x/Desktop/upscayl-2.9.8 linux/resources/app.asar.unpacked/node_modules/sharp/vendor/8.14.5/linux-x64/lib/libvips-cpp.so.42 + 0x330d83)
#1  0x8c53b8eb00000000 n/a (n/a + 0x0)
ELF object binary architecture: AMD x86-64
```
```

**Comment by NayamAmarshe** [comment]
This error seems related to sharp.js.
I didn't change anything in sharp, nor did I update the library so I'm not sure what's the issue here.

Could you try installing libvips manually? Maybe that might fix the issue?

**Comment by NayamAmarshe** [comment]
This error seems related to sharp.js. We added image conversion and scaling and compression in v2.8+ via Sharp.js which uses libvips.

It's possible that libvips is not supported by your system. Would it be possible for you to install libvips manually?

**Comment by NayamAmarshe** [comment]
https://github.com/directus/directus/issues/6307#issuecomment-1477437700

**Comment by NayamAmarshe** [comment]
This should be fixed in v2.11!

**Comment by AngryPenguinPL** [comment]
Yes, I can confirm, now works fine.
Thanks.
